[extraction]
executable = "c:\\temp\\149_auto\\extractor\\sap_automation.exe"
subcommand = "run-loop"                   # or "run-sequence" (runner warns if both loop)
args = []                                 # no additional args needed for your program
env = {}                                  # optional env for child process

[files]
output_dir = "c:\\temp\\reports\\y_149"
file_glob = "*_y_149-ALL.txt"             # defaults to "*.txt" if empty
filename_timestamp_prefix = true          # if true, can parse timestamp from filename
stable_size_check_secs = 2                # size must be stable for this many seconds

# Optional pre-upload normalization of TSV:
[transform]
enabled = false                           # if true, write a cleaned temp file to upload
format = "tsv"                            # "tsv" or "csv"
header_rows_to_skip = 6                   # skip non-data lines before the header row
header_match = "Plant\tDelivery\tMaterial" # sanity check (case-insensitive contains)
dedupe_rows = false                       # if true, drop duplicate data rows
trim_whitespace = true                    # trim cells
output_line_ending = "crlf"               # "crlf" or "lf"

[api]
endpoint = "https://api.example.com/upload.php"
mode = "lookup_enrich"                    # "multipart", "json_base64", or "lookup_enrich"
field_name = "file"                       # for multipart
extra_fields = {}                         # sent as additional form fields
json_filename_key = "filename"            # for json_base64
json_data_key = "data"
auth = "none"                             # "none" | "bearer" | "basic"
bearer_token = ""
basic_username = ""
basic_password = ""

[retry]
max_attempts = 3
initial_backoff_secs = 3                  # exponential, cap 30s

[loop]
interval_seconds = 300                    # 0 = run once; >0 = loop forever
allow_nested = true                       # allow nested loops since subcommand is run-loop

[archive]
enabled = false
path = "C:\\data\\archive"
append_timestamp = true                   # append YYYYMMDD_HHMMSS to archived name

# Optional lookup enrichment before upload
[lookup]
enabled = true                            # if true, enrich TSV data with lookup API
url = "http://api.example.com:5050/endpoint.php?ajax=lookup&part="
chunk_size = 200                          # max parts per lookup request
cookie = ""                               # optional session cookie
timeout_secs = 30                         # request timeout
post_url = "http://api.example.com:8080/blah/yadda.php"  # where to POST enriched data